from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import inch
import os

def generate_bill_pdf(amount, username, name, tid, email, date, stock, prediction):
    try:
        filename = f"{tid}-{username}.pdf"
        c = canvas.Canvas(filename, pagesize=A4)
        width, height = A4

        # Title Header
        c.setFillColor(colors.HexColor("#1F4E79"))  # Deep Blue
        c.setFont("Helvetica-Bold", 22)
        c.drawCentredString(width / 2.0, height - 80, "BullPOV Transaction Receipt")

        # Divider line
        c.setStrokeColor(colors.black)
        c.line(50, height - 90, width - 50, height - 90)

        # General Info
        c.setFont("Helvetica", 12)
        c.setFillColor(colors.black)
        y = height - 130

        details = [
            (f"Name:", name),
            (f"Username:", username),
            (f"Email:", email),
            (f"Transaction ID:", tid),
            (f"Transaction Date:", date),
            (f"Stock Traded:", stock),
            (f"Your Prediction:", prediction),
            (f"Transaction Status:", "Success"),
            (f"Platform Fee:", "0.00 Rupees"),
            (f"Net Amount Paid:", f"{amount:.2f} Rupees")
        ]

        for label, value in details:
            c.setFont("Helvetica-Bold", 11)
            c.drawString(75, y, f"{label}")
            c.setFont("Helvetica", 11)
            c.drawString(200, y, str(value))
            y -= 25

        # Footer Note
        c.setFont("Helvetica-Oblique", 10)
        c.setFillColor(colors.gray)
        c.drawString(75, y - 10, "Note: This is a system-generated receipt and does not require a signature.")

        # Branding Footer
        c.setFont("Helvetica-Bold", 10)
        c.setFillColor(colors.HexColor("#1F4E79"))
        c.drawRightString(width - 50, 40, "Generated by BullPOV")

        c.showPage()
        c.save()

        return None

    except Exception as e:
        return None