from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
import os

def generate_bill_pdf(amount, username, name):
    """
    Generate a simple bill PDF with the given amount and save it at the specified location.
    
    Args:
        amount (float or int): The amount to display on the bill.
        save_path (str): File path where the PDF should be saved.
        
    Returns:
        None
    """
    try:
        # Create a canvas object for PDF
        c = canvas.Canvas(f"{username}.pdf", pagesize=A4)
        width, height = A4

        # Set title and content
        c.setFont("Helvetica-Bold", 20)
        c.drawCentredString(width / 2.0, height - 100, "INVOICE / BILL")

        c.setFont("Helvetica", 12)
        c.drawString(100, height - 150, "Thank you for your purchase!")
        c.drawString(100, height - 180, f"Amount Paid: ₹{amount:.2f}")
        
        c.drawString(100, height - 220, "Generated by OrcaBeam Billing System")
        c.drawString(100, height - 250, "This is a computer-generated bill and does not require a signature.")
        
        # Finalize the PDF
        c.showPage()
        c.save()

    except Exception as e:
        print("Error generating bill:", e)

# Example usage
generate_bill_pdf(1299.50)
