# Generated by Django 5.2.1 on 2025-06-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0002_rename_userdetails_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='ForgotPassword',
            field=models.CharField(default=''),
        ),
    ]
