# Generated by Django 5.2.1 on 2025-06-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0003_userdetail_forgotpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='ForgotPassword',
            new_name='ForgotPasswordOTP',
        ),
    ]
