# Generated by Django 5.2.1 on 2025-06-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0004_rename_forgotpassword_userdetail_forgotpasswordotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='PhoneNumber',
            field=models.CharField(default=''),
        ),
    ]
