# Generated by Django 5.2 on 2025-06-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0005_userdetail_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='Country',
            field=models.CharField(default='India'),
        ),
    ]
