# Generated by Django 5.2 on 2025-06-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0006_userdetail_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='VerifiedAccount',
            field=models.BooleanField(default=False),
        ),
    ]
