# Generated by Django 5.2 on 2025-06-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0007_userdetail_verifiedaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='VerificationOTP',
            field=models.CharField(default=''),
        ),
    ]
