# Generated by Django 5.2 on 2025-06-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0008_userdetail_verificationotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='')),
                ('Logo', models.ImageField(upload_to='')),
                ('Symbol', models.CharField(default='')),
                ('Sector', models.CharField(default='')),
                ('CurrentPrice', models.FloatField()),
                ('DayHigh', models.FloatField()),
                ('DayLow', models.FloatField()),
                ('OpeningPrice', models.FloatField()),
                ('ClosingPrice', models.FloatField()),
                ('PriceChange', models.FloatField()),
                ('Volume', models.IntegerField()),
                ('MktCap', models.FloatField()),
                ('PERatio', models.FloatField()),
                ('DividendYield', models.FloatField()),
                ('EPS', models.FloatField()),
                ('LastUpdateTime', models.DateField()),
                ('UPUsers', models.IntegerField()),
                ('DownUsers', models.IntegerField()),
                ('TotalUsers', models.IntegerField()),
            ],
        ),
    ]
