# Generated by Django 5.2 on 2025-06-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0009_stocks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stocks',
            new_name='Stock',
        ),
    ]
