# Generated by Django 5.2 on 2025-06-26 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0010_rename_stocks_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ClosingPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='CurrentPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='DayHigh',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='DayLow',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='DividendYield',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='DownUsers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='EPS',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 6, 27, 1, 35, 17, 821287)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Logo',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='MktCap',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='OpeningPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='PERatio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='PriceChange',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='TotalUsers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='UPUsers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Volume',
            field=models.IntegerField(default=0),
        ),
    ]
