# Generated by Django 5.2 on 2025-07-05 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0011_alter_stock_closingprice_alter_stock_currentprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Nifty50',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 5, 23, 56, 57, 320024)),
        ),
    ]
