# Generated by Django 5.2 on 2025-07-07 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0013_stock_topgainer_alter_stock_lastupdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='TopLoser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 8, 0, 6, 13, 910616)),
        ),
    ]
