# Generated by Django 5.2 on 2025-07-07 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0014_stock_toploser_alter_stock_lastupdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 8, 1, 36, 35, 844298)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='MktCap',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Volume',
            field=models.CharField(default=0),
        ),
    ]
