# Generated by Django 5.2 on 2025-07-11 10:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0015_alter_stock_lastupdatetime_alter_stock_mktcap_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 11, 16, 2, 14, 497747)),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField(default=0)),
                ('DateTime', models.CharField(default='')),
                ('Prediction', models.BooleanField(default=None)),
                ('Stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StockDetails', to='BullPOVApp.stock')),
                ('Trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TraderDetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
