# Generated by Django 5.2 on 2025-07-11 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0016_alter_stock_lastupdatetime_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='ActiveStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 11, 17, 3, 22, 744598)),
        ),
    ]
