# Generated by Django 5.2 on 2025-07-11 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0017_trade_activestatus_alter_stock_lastupdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='Address',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='ProfilePhoto',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='UPI',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 11, 19, 18, 52, 127278)),
        ),
    ]
