# Generated by Django 5.2 on 2025-07-11 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0018_userdetail_address_userdetail_profilephoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='WalletBalance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 12, 0, 1, 58, 829267)),
        ),
    ]
