# Generated by Django 5.2 on 2025-07-11 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0019_userdetail_walletbalance_alter_stock_lastupdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='Return',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 12, 0, 29, 16, 118090)),
        ),
    ]
