# Generated by Django 5.2 on 2025-07-13 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0021_alter_stock_lastupdatetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='ForgotPasswordOTP',
            new_name='OTPEmail',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='OTPPhone',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 13, 21, 5, 38, 575103)),
        ),
    ]
