# Generated by Django 5.2 on 2025-07-13 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0022_rename_forgotpasswordotp_userdetail_otpemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 13, 23, 7, 45, 721054)),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='ProfilePhoto',
            field=models.ImageField(default='default.png', upload_to='ProfilePhotos/'),
        ),
    ]
