# Generated by Django 5.2 on 2025-07-13 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0023_alter_stock_lastupdatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='Watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchList', to='BullPOVApp.stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 14, 0, 1, 33, 243467)),
        ),
    ]
