# Generated by Django 5.2 on 2025-07-13 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0024_userdetail_watchlist_alter_stock_lastupdatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='')),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Subject', models.CharField(default='')),
                ('Message', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 14, 1, 15, 41, 243015)),
        ),
    ]
