# Generated by Django 5.2 on 2025-07-14 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0025_contact_alter_stock_lastupdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='MaxPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='MinPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 15, 0, 49, 41, 766932)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='MktCap',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Volume',
            field=models.FloatField(default=0),
        ),
    ]
