# Generated by Django 5.2 on 2025-07-14 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0026_stock_maxprice_stock_minprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='MaxPrice',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='MinPrice',
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 15, 0, 56, 8, 520293)),
        ),
    ]
