# Generated by Django 5.2 on 2025-07-15 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0027_remove_stock_maxprice_remove_stock_minprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Description',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 15, 21, 16, 23, 510754)),
        ),
    ]
