# Generated by Django 5.2 on 2025-07-15 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0028_stock_description_alter_stock_lastupdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 15, 21, 28, 25, 818469)),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='ProfilePhoto',
            field=models.ImageField(default='/default.png', upload_to='ProfilePhotos/'),
        ),
    ]
