# Generated by Django 5.2 on 2025-07-15 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0029_alter_stock_lastupdatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='InvestedBalance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 16, 1, 21, 24, 418956)),
        ),
    ]
