# Generated by Django 5.2 on 2025-07-16 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0030_userdetail_investedbalance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='TotalUsers',
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 17, 0, 1, 7, 626038)),
        ),
    ]
