# Generated by Django 5.2 on 2025-07-16 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0031_remove_stock_totalusers_alter_stock_lastupdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='Outcome',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 17, 1, 19, 43, 385351)),
        ),
    ]
