# Generated by Django 5.2 on 2025-07-16 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0032_trade_outcome_alter_stock_lastupdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='UPI',
        ),
        migrations.AddField(
            model_name='trade',
            name='Receipt',
            field=models.FileField(default='', upload_to='Receipts/'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 17, 2, 27, 37, 763052)),
        ),
    ]
