# Generated by Django 5.2 on 2025-07-17 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0033_remove_userdetail_upi_trade_receipt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='ClosingPrice',
            new_name='CurrentPriceToday',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='CurrentPrice',
            new_name='CurrentPriceYesterday',
        ),
        migrations.AddField(
            model_name='stock',
            name='PreviousCloseToday',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='PreviousCloseYesterday',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 18, 1, 42, 17, 691902)),
        ),
    ]
