# Generated by Django 5.2 on 2025-07-17 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0034_rename_closingprice_stock_currentpricetoday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='CurrentPriceToday',
            new_name='CurrentPrice',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='CurrentPriceYesterday',
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 18, 1, 46, 41, 881865)),
        ),
    ]
