# Generated by Django 5.2 on 2025-07-23 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0035_rename_currentpricetoday_stock_currentprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='TradeID',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 24, 0, 35, 35, 229043)),
        ),
    ]
