# Generated by Django 5.2 on 2025-07-24 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0036_trade_tradeid_alter_stock_lastupdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 24, 20, 56, 17, 82388)),
        ),
        migrations.AlterField(
            model_name='trade',
            name='Receipt',
            field=models.CharField(default=''),
        ),
    ]
