# Generated by Django 5.2 on 2025-07-25 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0037_alter_stock_lastupdatetime_alter_trade_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(default='', max_length=10000)),
                ('Shoot', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 25, 22, 27, 1, 308693)),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='Notifications',
            field=models.ManyToManyField(blank=True, related_name='watchList', to='BullPOVApp.notification'),
        ),
    ]
