# Generated by Django 5.2 on 2025-07-25 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0038_notification_alter_stock_lastupdatetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='Notifications',
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 26, 0, 32, 31, 729310)),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
