# Generated by Django 5.2 on 2025-07-26 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0039_remove_userdetail_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 26, 20, 32, 39, 475659)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Logo',
            field=models.CharField(),
        ),
    ]
