# Generated by Django 5.2 on 2025-07-27 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0040_alter_stock_lastupdatetime_alter_stock_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samachaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='')),
                ('Category', models.CharField(default='')),
                ('Date', models.CharField(default='')),
                ('Source', models.CharField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 28, 0, 24, 0, 106281)),
        ),
    ]
