# Generated by Django 5.2 on 2025-07-27 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0041_samachaar_alter_stock_lastupdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='samachaar',
            name='Image',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 28, 0, 27, 7, 505044)),
        ),
    ]
