# Generated by Django 5.2 on 2025-07-27 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0042_samachaar_image_alter_stock_lastupdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='samachaar',
            name='Link',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 28, 0, 33, 21, 272041)),
        ),
    ]
