# Generated by Django 5.2 on 2025-07-28 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0045_alter_stock_lastupdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='LastUpdateTime',
            field=models.DateField(default=datetime.datetime(2025, 7, 29, 1, 26, 32, 20235)),
        ),
    ]
