# Generated by Django 5.2 on 2025-07-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0049_alter_stock_lastupdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='LastUpdateTime',
        ),
    ]
