# Generated by Django 5.2 on 2025-07-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0050_remove_stock_lastupdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='DOB',
            field=models.CharField(default=''),
        ),
    ]
