# Generated by Django 5.2 on 2025-07-31 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0051_userdetail_dob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField(default=0)),
                ('Action', models.BooleanField(default=False)),
                ('LoggedINEmail', models.CharField(default='')),
                ('OrderID', models.CharField(default='')),
                ('TxnID', models.CharField(default='')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TxnDetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
