# Generated by Django 5.2 on 2025-07-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0052_wallettxn'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettxn',
            name='Status',
            field=models.CharField(default=''),
        ),
    ]
