# Generated by Django 5.2 on 2025-08-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0053_wallettxn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettxn',
            name='WithdrawalUPI',
            field=models.CharField(default=''),
        ),
    ]
