# Generated by Django 5.2 on 2025-08-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0054_wallettxn_withdrawalupi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettxn',
            name='LoggedINEmail',
        ),
    ]
