# Generated by Django 5.2 on 2025-08-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0056_wallettxn_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='DateTime',
            field=models.CharField(default=''),
        ),
    ]
