# Generated by Django 5.2 on 2025-08-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0057_contact_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettxn',
            name='ID',
            field=models.CharField(default=''),
        ),
    ]
