# Generated by Django 5.2 on 2025-08-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0058_wallettxn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='TopVolume',
            field=models.BooleanField(default=False),
        ),
    ]
