# Generated by Django 5.2 on 2025-08-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0059_stock_topvolume'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='TopTraded',
            field=models.BooleanField(default=False),
        ),
    ]
