# Generated by Django 5.2 on 2025-08-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0060_stock_toptraded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='TopTraded',
        ),
    ]
