# Generated by Django 5.2 on 2025-08-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0061_remove_stock_toptraded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='CurrentPrice',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='DownUsers',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='MktCap',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Nifty50',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='OpeningPrice',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='PreviousCloseToday',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='PreviousCloseYesterday',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='PriceChange',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Sector',
            field=models.CharField(db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Symbol',
            field=models.CharField(db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='TopGainer',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='TopLoser',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='TopVolume',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='UPUsers',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Volume',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
