# Generated by Django 5.2 on 2025-08-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0062_alter_stock_currentprice_alter_stock_downusers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='PlatformCut',
            field=models.FloatField(default=0),
        ),
    ]
