# Generated by Django 5.2 on 2025-08-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BullPOVApp', '0063_stock_platformcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='PlatformCut',
            field=models.FloatField(default=5),
        ),
    ]
